// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// del2D_cpp
Rcpp::List del2D_cpp(Rcpp::NumericMatrix pts);
RcppExport SEXP _delaunay_del2D_cpp(SEXP ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pts(ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(del2D_cpp(pts));
    return rcpp_result_gen;
END_RCPP
}
// del2DC_cpp
Rcpp::List del2DC_cpp(Rcpp::NumericMatrix pts, Rcpp::IntegerMatrix edges);
RcppExport SEXP _delaunay_del2DC_cpp(SEXP ptsSEXP, SEXP edgesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type edges(edgesSEXP);
    rcpp_result_gen = Rcpp::wrap(del2DC_cpp(pts, edges));
    return rcpp_result_gen;
END_RCPP
}
// del3D_cpp
Rcpp::List del3D_cpp(Rcpp::NumericMatrix pts);
RcppExport SEXP _delaunay_del3D_cpp(SEXP ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pts(ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(del3D_cpp(pts));
    return rcpp_result_gen;
END_RCPP
}
// del3D_cpp_hullinfo
Rcpp::List del3D_cpp_hullinfo(Rcpp::NumericMatrix pts);
RcppExport SEXP _delaunay_del3D_cpp_hullinfo(SEXP ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pts(ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(del3D_cpp_hullinfo(pts));
    return rcpp_result_gen;
END_RCPP
}
// delXY_cpp
Rcpp::List delXY_cpp(Rcpp::NumericMatrix pts);
RcppExport SEXP _delaunay_delXY_cpp(SEXP ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pts(ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(delXY_cpp(pts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_delaunay_del2D_cpp", (DL_FUNC) &_delaunay_del2D_cpp, 1},
    {"_delaunay_del2DC_cpp", (DL_FUNC) &_delaunay_del2DC_cpp, 2},
    {"_delaunay_del3D_cpp", (DL_FUNC) &_delaunay_del3D_cpp, 1},
    {"_delaunay_del3D_cpp_hullinfo", (DL_FUNC) &_delaunay_del3D_cpp_hullinfo, 1},
    {"_delaunay_delXY_cpp", (DL_FUNC) &_delaunay_delXY_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_delaunay(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
