# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

del2D_cpp <- function(pts) {
    .Call(`_delaunay_del2D_cpp`, pts)
}

del2DC_cpp <- function(pts, edges) {
    .Call(`_delaunay_del2DC_cpp`, pts, edges)
}

del3D_cpp <- function(pts) {
    .Call(`_delaunay_del3D_cpp`, pts)
}

del3D_cpp_hullinfo <- function(pts) {
    .Call(`_delaunay_del3D_cpp_hullinfo`, pts)
}

delXY_cpp <- function(pts) {
    .Call(`_delaunay_delXY_cpp`, pts)
}

